var LinnearRollingGuideDetailCtrl=angular.module("LinnearRollingGuideDetailCtrl",[]);
//直线导轨详情页控制器
LinnearRollingGuideDetailCtrl.controller("LinnearRollingGuideDetailCtrl",function($scope,$state,$stateParams,$http,$cookies){
	$scope.guid={};
	$http({
		method:"GET",
		url:"http://cncdataapi.azurewebsites.net/api/cncdata/LineRollingGuides",
		params:{
			id:$stateParams.id
		}
	}).success(function(data){
		$scope.guid=data;
	});
	$scope.nextStep=function(){
		$cookies.putObject($stateParams.FeedSystemType+"LinearRollingGuide",$scope.guid);
		$state.go("FeedSystem.SolidBallScrewNutPairs");
	};
	$scope.back=function(){
		$state.go("FeedSystem");
	};
});